export const CATEGORY_PRODUCT_LIST_REQUEST = "CATEGORY_PRODUCT_LIST_REQUEST";
export const CATEGORY_PRODUCT_LIST_SUCCESS = "CATEGORY_PRODUCT_LIST_SUCCESS";
export const CATEGORY_PRODUCT_LIST_FAIL = "CATEGORY_PRODUCT_LIST_FAIL";